services:
  db:
    image: postgres:18
    container_name: cookify_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always
  
  cookify.api:
    image: cookify.api
    build:
      context: .
      dockerfile: Cookify.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: cookify_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_SECRET_KEY}
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    
volumes:
  postgres_data: